### PR TITLE
Thunderlaseradditionaloptions

### PR DESCRIPTION
**Pull request by mrlinux1**
@kkaempf Please review ;-)

Added LaserPowerMin property in ThunderLaser properties.

### CODE REVIEW

**Comment by jnweiger** [comment]
ALL: Please close and ignore here and now. We'll come back later :-)

**Comment by t-oster** [comment]
we'll wait for you

**Comment by kkaempf** [comment]
@jnweiger spoiling the party :rofl:

**Comment by kkaempf** [comment]
@mrlinux1 please open the pr against https://github.com/kkaempf/LibLaserCut#thunderlaser, thanks !

**Comment by jnweiger** [comment]
psst, top secret :-)
@kkaempf -> https://github.com/kkaempf/LibLaserCut/pull/1

@t-oster If you know some impatient inkscape fans, send them here: https://github.com/jnweiger/inkscape-thunderlaser/releases (everthing already implemented, only the wrong programming language :-) )

**Pull request closed without merging**
