### PR TITLE
create test coverage statistics

### PR DESCRIPTION
**Pull request by mgmax**
I'd like to set up automatic test coverage reports for new pull requests.
This should be possible with codacy, as far as *internal* pull requests (not from external contributors with their own forks) are concerned. @t-oster can you please set up `CODACY_PROJECT_TOKEN` as a secret travis environment variable? https://support.codacy.com/hc/en-us/articles/207279819-Coverage 

However, it seems impossible by design with codacy to check coverage of *external* pull requests, which would actually be the most important part.

### CODE REVIEW

**Comment by t-oster** [comment]
Hi @mgmax, I added a token to VisiCut and LibLaserCut each...

**Comment by mgmax** [comment]
Hi @t-oster , can you please check if codacy is actually enabled for LibLaserCut? I don't see the codacy check (anymore?) for the commits, only Travis CI is shown (for example in this PR, if you click on "show all checks").

**Comment by t-oster** [comment]
Hi @mgmax I am not sure what is wrong. Travis showed it successfully uploaded the coverage (see https://travis-ci.org/github/t-oster/LibLaserCut/builds/668320880?utm_source=github_status&utm_medium=notification) but in Codacy I cannot see any coverage report.

**Comment by t-oster** [comment]
maybe it has to be present in master first?

**Comment by t-oster** [comment]
@mgmax yep, now it's showing in Codacy, so it had to be in master first (wtf?)

**Pull request merged**
