### PR TITLE
Move properties into separate package

### PR DESCRIPTION
**Pull request by TheAssassin**
This cleanup makes working with them more convenient.

Counterpart of https://github.com/t-oster/VisiCut/pull/725.

### CODE REVIEW

**Comment by mgmax** [comment]
Looks good.

- Please resolve conflicts - I can't click the merge button otherwise :-)
- Can you do some testing to make sure that this does not break loading old VisiCut settings?
   - Suggestion: In the previous VisiCut version, create several laser devices and save some material settings, so that you have XML laserprofile files for each of the property classes that are moved (PowerSpeedFocusFrequencyProperty, ..., whatever). Then look that in the new version you still see the old values. 
- Once this is merged, you can update the PR in VisiCut so that it also includes the new version of the LibLaserCut submodule, and then we can merge that too.

**Comment by TheAssassin** [comment]
I suggest you merge this PR, then I can update a variety of others.

**Comment by mgmax** [comment]
The tests fail because you deleted one Java file. Please try again :)

**Comment by TheAssassin** [comment]
Somehow, rebasing in this repository is my arch nemesis. Anyway. Let's try again.

**Comment by TheAssassin** [comment]
Here we go.

**Review by mgmax — APPROVED** [review]

**Comment by mgmax** [comment]
Thanks :-)

**Pull request merged**
