### PR TITLE
Avoid errors with unsupported starting point

### PR DESCRIPTION
**Pull request by mgmax**
- Raise error message to avoid https://github.com/t-oster/VisiCut/issues/496
- Add dump utility and example files to help with troubleshooting the Epilog driver

### CODE REVIEW

**Comment by t-oster** [comment]
Shouldn't we investigate further before just blocking that Feature? I am pretty sure I cut some stuff with a centered starting point with an Epilog Zing

**Comment by mgmax** [comment]
@t-oster is there any chance of getting this merged? The data we are sending doesn't match what the official Epilog driver does, so I don't think we are doing it right and we should rather disable the feature now.

If you don't want to merge, then I will send everything unrelated to the Epilog change as a new pull request.

**Comment by t-oster** [comment]
If you can confirm that a vector job with starting point in the middle is not correctly executed when using the x/y off button to manually position the laser head, then we can merge, but I used it exactly that way on an epilog zing and it did work with negative coordinates. Unfortunately I do not live in Aachen anymore so I don't have access to the zing anymore

**Comment by mgmax** [comment]
@t-oster I also don't have the possibility to test it right now. How about changing the error message into a warning like "This may not work. Please report if it works at https://github.com/t-oster/VisiCut/issues/496 " ?

**Comment by t-oster** [comment]
Yes, I could live with that.

**Comment by mgmax** [comment]
Okay, so now you should be able to merge this and #100.

**Pull request merged**
