### PR TITLE
Fixed dangling Javadoc comments

### PR DESCRIPTION
**Pull request by phdoerfler**
Having Javadoc at the beginning of a .java file is an error. I converted these into block comments.

### CODE REVIEW

**Comment by t-oster** [comment]
We have to update the test.sh/COPYRIGHTHEADER also

**Comment by phdoerfler** [comment]
/sighs/ I did run test.sh locally and it didn't complain.

**Comment by phdoerfler** [comment]
this is a pain, I wish we were using https://github.com/sbt/sbt-header or whatever equivalent there is in maven land

**Comment by phdoerfler** [comment]
Dunno why test.sh did not complain before. I guess I must have run it on the visicut repository accidentally. Anyways, it should™ be fixed now.

**Comment by t-oster** [comment]
Feel free to migrate it to whatever you think fits better

**Pull request merged**
