### PR TITLE
Smoothieboard Support

### PR DESCRIPTION
**Pull request by t-oster**
This is the official Smoothieboard development pull-request. All suggestions specific to the new smoothieboard driver should go in this pull-request.

TODO:
- [x] Auto COM-Port detection for serial connection
- [ ] Test serial library
 - [x] Linux
 - [ ] Windows
 - [x] OSX
- [x] Ethernet connection (telnet)
- [x] Raster-To-Vector conversion (tested for small object without lasercutter yet)
- [ ] Raster 3d To Vector conversion
- [X] Flow Control: Does the smoothieboard support/need RTS/CTS serial flow control or is it enough to wait for the "OK" answers? -> @arthurwolf sais waiting for "OK" is enough https://github.com/t-oster/LibLaserCut/issues/21#issuecomment-123244080
- [ ] Job-Based upload: Enable sending jobs to the SD Card instead of direct sending via serial/telnet
 - [x] Ethernet: ~~SFTP Protocol~~ HTTP Upload like in the web interface (https://github.com/t-oster/LibLaserCut/issues/21#issuecomment-123244080)
 - [ ] USB: Also telnet? Output to mouted sd card is not good because card should not be mounted
- [x] Split into general Gcode/Grbl driver and SmoothieBoard which is an instance of this driver with useful default values
- [x] Add possiblity for startup- and shutdown-gcode
- [x] Add M3 to startup-gcode by default?
- [x] Fix range of S-Parameter from 0-100 to 0-1

Build for Testers:
http://download.visicut.org/smoothie

### CODE REVIEW

**Comment by peteruithoven** [comment]
Would the Smoothieboard also be controllable over a local network (via the Ethernet port)?

**Comment by t-oster** [comment]
Yes, currently the driver supoorts connecting via USB (serial) or Telnet (Ethernet). If you specify both, Ethernet is default.

**Comment by t-oster** [comment]
It seems as if the RTS/CTS flow control is never triggered (in my tests), so it seems to be sufficient to wait for the "ok" messages sent back from the board. I did not yet try very lage jobs though.

**Comment by thinkl33t** [comment]
Playing around with this at the moment, any chance of configuration options for a start.gcode and end.gcode?  My laser is set up with extraction and air assist on switch modules, using the reprap-style M106/M107 commands

**Comment by t-oster** [comment]
I will add this tomorrow. I will also split the driver into a general g-code driver with many configuration options and a smoothie-specific instance, which has smoothie-specific defaults for that driver.

**Comment by t-oster** [comment]
Please test if the pre/post g-code feature works as expected.The build is updated.

**Comment by t-oster** [comment]
Ok. I tested HTTP,Serial and HTTP_Upload with Smoothieboard. It works. Also the DPI, the lineend and the Baud-rate are configurable for the generic grbl driver. Builds are updated, please test everything

**Comment by Tamagotono** [comment]
I am using version 1.7-256 of the Smoothie branch, and am having an issue. VisiCut will connect up and go through the motions, but never actually cuts or etches anything. I believe that it is giving the command to fire, but it has no power setting. If I hold down on the TEST button on the Laser Power Supply, while it is running, it will fire the laser in the proper spots, but at 100% power.
I can use the laser without issues via Pronterface. What information do you need from me to troubleshoot this issue?

I am using an Azteeg X5 mini on a K40 machine.

**Comment by arthurwolf** [comment]
Hey.

This may not be a VisiCut problem, maybe it's a Smoothie/wiring problem.

Can you please try installing Pronterface, and sending to the board :
G1 X10
G0 X20
The first command should move and cut, the second one should move without
cutting.
If that's not what you see, you have a non-Visicut problem, and we'll work
on that on the Smoothie side.

Cheers.


On Sun, Jul 26, 2015 at 1:10 PM, Tamagotono <notifications@github.com>
wrote:

> I am using version 1.7-256 of the Smoothie branch, and am having an issue.
> VisiCut will connect up and go through the motions, but never actually cuts
> or etches anything. I believe that it is giving the command to fire, but it
> has no power setting. If I hold down on the TEST button on the Laser Power
> Supply, while it is running, it will fire the laser in the proper spots,
> but at 100% power.
> I can use the laser without issues via Pronterface. What information do
> you need from me to troubleshoot this issue?
>
> I am using an Azteeg X5 mini on a K40 machine.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/t-oster/LibLaserCut/pull/23#issuecomment-124972425>.
>



-- 
Courage et bonne humeur.

**Comment by Tamagotono** [comment]
Arthur,
 I did the test as you requested. Issuing the commands via Pronterface replicated the problem I had with VisiCut. The laser did not fire while issuing either command, but the axis did move.
 I also tried issuing the commands while holding down on the TEST button on the laser power supply, and the laser did not fire with the G0 X20 command, but did with the G1 X10 command. Where would be the proper place to report this for the Smoothieware. I know you will work on it, but thought it might need to go in a bug tracker somewhere for documentation purposes.

Please let me know if there is anything I can do to help with this.

**Comment by arthurwolf** [comment]
Hey.

This is most clearly a mis-wiring problem. You can discuss this in the
smoothie mailing list, or in the smoothie irc channel, both are linked to
in the smoothieware.org website.

Cheers.

On Sun, Jul 26, 2015 at 10:49 PM, Tamagotono <notifications@github.com>
wrote:

> Arthur,
> I did the test as you requested. Issuing the commands via Pronterface
> replicated the problem I had with VisiCut. The laser did not fire while
> issuing either command, but the axis did move.
> I also tried issuing the commands while holding down on the TEST button on
> the laser power supply, and the laser did not fire with the G0 X20 command,
> but did with the G1 X10 command. Where would be the proper place to report
> this for the Smoothieware. I know you will work on it, but thought it might
> need to go in a bug tracker somewhere for documentation purposes.
>
> Please let me know if there is anything I can do to help with this.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/t-oster/LibLaserCut/pull/23#issuecomment-125037543>.
>



-- 
Courage et bonne humeur.

**Comment by Tamagotono** [comment]
I found the problem! 
Since Pronterface would work while running externally generated gcode, but not the codes supplied by arthurwolf, I dug into the gcode and realized that I needed to add "M3" to the starting gcode in the configuration file. After doing this, my laser cutter now fires! Unfortunately, it fires at 100% power, regardless of the "Power" setting under "Laser Settings". Is it possible the "Power" setting is sent to the Smoothieboard as a value 0-100 instead of 0-1?

**Comment by arthurwolf** [comment]
Hey.

Please upgrade your config file and firmware to the latest version, it
-might- fix that problem.

On Sun, Jul 26, 2015 at 11:40 PM, Tamagotono <notifications@github.com>
wrote:

> I found the problem!
> Since Pronterface would work while running externally generated gcode, but
> not the codes supplied by arthurwolf, I dug into the gcode and realized
> that I needed to add "M3" to the starting gcode in the configuration file.
> After doing this, my laser cutter now fires! Unfortunately, it fires at
> 100% power, regardless of the "Power" setting under "Laser Settings". Is it
> possible the "Power" setting is sent to the Smoothieboard as a value 0-100
> instead of 0-1?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/t-oster/LibLaserCut/pull/23#issuecomment-125042620>.
>



-- 
Courage et bonne humeur.

**Comment by Tamagotono** [comment]
I have updated the firmware and configuration files with the latest edge version. There is no change in the behavior.

I realized that by launching visicut from a console, I get to see all of the commands sent, and have verified my theory is correct, it is sending power levels in the range of 0-100 instead of 0-1.  The following line was sent by VisiCut with a Power Setting of 1 (lowest possible value) which I assume is 1%...
<code>
> > G1 X52.070000 Y126.949200 S1.000000 F3000
</code>
So for Smoothie, the "S" value should be "S0.01" not "S1.000000".

**Comment by t-oster** [comment]
Hi,
you're right. I will update the driver to output 0.000-1.00 instead of  1-100. @arthurwolf I just noticed, that a G0 command is used in the wiki http://smoothieware.org/laser to explain the S-Parameter, which may be misleading, because it only affects G1 commands?

@Tamagotono So you need the M3 command only once on job-begin? Then I can add this as default, but you can also add this to the "pre-job-gcode" setting in the lasercutter settings in VisiCut.

**Comment by arthurwolf** [comment]
@t-oster : Thanks, fixed the error in the documentation. The S parameter
will actually be taken into account anywhere it's used, but the
documentation should have a G1 there for clarity.

About M3, you also want a M5 at the end of the job to turn the PSU off.

On Mon, Jul 27, 2015 at 10:21 AM, Thomas Oster <notifications@github.com>
wrote:

> Hi,
> you're right. I will update the driver to output 0.000-1.00 instead of
> 1-100. @arthurwolf <https://github.com/arthurwolf> I just noticed, that a
> G0 command is used in the wiki http://smoothieware.org/laser to explain
> the S-Parameter, which may be misleading, because it only affects G1
> commands?
>
> @Tamagotono <https://github.com/Tamagotono> So you need the M3 command
> only once on job-begin? Then I can add this as default, but you can also
> add this to the "pre-job-gcode" setting in the lasercutter settings in
> VisiCut.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/t-oster/LibLaserCut/pull/23#issuecomment-125122716>.
>



-- 
Courage et bonne humeur.

**Comment by t-oster** [comment]
@arthurwolf so M3/M5 is default wiring/setting for the smoothieboard in lasercutter-mode? The I will add this to the default pre/pos job gcodes.

**Comment by arthurwolf** [comment]
On Mon, Jul 27, 2015 at 10:50 AM, Thomas Oster <notifications@github.com>
wrote:

> @arthurwolf <https://github.com/arthurwolf> so M3/M5 is default
> wiring/setting for the smoothieboard in lasercutter-mode? The I will add
> this to the default pre/pos job gcodes.
>

@t-oster : Most laser PSUs have two inputs : one that enables the PSU, and
one that sets the power ( via PWM ).
Most people actually just hard-wire the enable one high, and only use the
PWM to control power -and- whether it's on or off.
But you -can- connect the enable signal to Smoothieboard, in which case M3
enables and M5 disables. So might as well put those at the beginning and
end for people that need it.

> —
> Reply to this email directly or view it on GitHub
> <https://github.com/t-oster/LibLaserCut/pull/23#issuecomment-125132027>.
>



-- 
Courage et bonne humeur.

**Comment by t-oster** [comment]
done.

**Comment by t-oster** [comment]
@Tamagotono Despite the fact, that the power is now converted to 0-1, it is now also possible to use fractions for power and speed like 0.2 etc.

**Comment by Tamagotono** [comment]
Wow, you work fast! Thank you.
My laser cutter is now firing and can vary the power level, however, whenever I try to do a cut or mark, it returns an error. Below is the full output from the time I hit the "execute" button to the time the error shows up (a few seconds).
`< Smoothie command shell
> G21
< > ok
> G90
< ok
> M3
< ok
java.lang.ClassCastException: com.t_oster.liblasercut.FloatPowerSpeedFocusProperty cannot be cast to com.t_oster.liblasercut.PowerSpeedFocusProperty
        at com.t_oster.liblasercut.drivers.GenericGcodeDriver.writeVectorGCode(GenericGcodeDriver.java:252)
        at com.t_oster.liblasercut.drivers.GenericGcodeDriver.sendJob(GenericGcodeDriver.java:575)
        at com.t_oster.visicut.VisicutModel.sendJob(VisicutModel.java:723)
        at com.t_oster.visicut.gui.MainView$61.run(MainView.java:1843)`

Also, I have one other annoying issue. Frequently, when I try to execute a job, it says that the port is already in use, even if VisiCut had just used it. Of course this is via the USB cable, as my Azteeg X5 mini does not have a network port.  

By the way, is this the proper place to be reporting issues or should I be posting them somewhere else?

Thanks again for all of your hard work! I am excited to be able to use such a well rounded utility.

**Comment by t-oster** [comment]
Hi,please delete your lasercutter settings and create new ones or delete the whole visicut folder. It seems as if there are still old laser settings present.i think the port is not properly closed when the exceptions occur so please check if the error goes away. 
It is the right place to report errors. Thank you for testing

-------- Ursprüngliche Nachricht --------
Von: Tamagotono <notifications@github.com> 
Datum:28.07.2015  06:22  (GMT+01:00) 
An: t-oster/LibLaserCut <LibLaserCut@noreply.github.com> 
Cc: Thomas Oster <thomas.oster@rwth-aachen.de> 
Betreff: Re: [LibLaserCut] Smoothieboard Support (#23) 

Wow, you work fast! Thank you.
My laser cutter is now firing and can vary the power level, however, whenever I try to do a cut or mark, it returns an error. Below is the full output from the time I hit the "execute" button to the time the error shows up (a few seconds).
`< Smoothie command shell

G21
< > ok
G90
< ok
M3
< ok
java.lang.ClassCastException: com.t_oster.liblasercut.FloatPowerSpeedFocusProperty cannot be cast to com.t_oster.liblasercut.PowerSpeedFocusProperty
at com.t_oster.liblasercut.drivers.GenericGcodeDriver.writeVectorGCode(GenericGcodeDriver.java:252)
at com.t_oster.liblasercut.drivers.GenericGcodeDriver.sendJob(GenericGcodeDriver.java:575)
at com.t_oster.visicut.VisicutModel.sendJob(VisicutModel.java:723)
at com.t_oster.visicut.gui.MainView$61.run(MainView.java:1843)`

Also, I have one other annoying issue. Frequently, when I try to execute a job, it says that the port is already in use, even if VisiCut had just used it. Of course this is via the USB cable, as my Azteeg X5 mini does not have a network port.

By the way, is this the proper place to be reporting issues or should I be posting them somewhere else?

Thanks again for all of your hard work! I am excited to be able to use such a well rounded utility.

**Comment by Tamagotono** [comment]
OK,
 So I tried deleting just my settings folder, and that didn't help. I then tried deleting the entire .visicut folder in my home directory, and that didn't help. Next, I deleted the .visicut folder and uninstalled/reinstalled the latest version of visicut (1.7-259-gib70a1f), and I am still getting the same error whenever I try to do a cut.

If there is anything else you would like me to try, please let me know and I will be happy to try when I get home from work tomorrow.

Also, I was wondering if there is a way to abort a job once it has been sent to the cutter.

**Comment by t-oster** [comment]
my bad, should work now.

**Comment by Tamagotono** [comment]
Well, it is working much better. I am now able to cut without the casting error. I am now having two other issues, one is very repeatable, the other is intermittent.

The repeatable one first:
After every job, regardless of if it completes properly or encounters an error, the port is not released, so I am unable to execute another job until I restart VisiCut. 

The intermittent one:
During a cut, the job will stop and shows the following error in the console:
```java
java.io.IOException: Underlying input stream returned zero bytes
	at sun.nio.cs.StreamDecoder.readBytes(StreamDecoder.java:288)
	at sun.nio.cs.StreamDecoder.implRead(StreamDecoder.java:326)
	at sun.nio.cs.StreamDecoder.read(StreamDecoder.java:178)
	at java.io.InputStreamReader.read(InputStreamReader.java:184)
	at java.io.BufferedReader.fill(BufferedReader.java:161)
	at java.io.BufferedReader.readLine(BufferedReader.java:324)
	at java.io.BufferedReader.readLine(BufferedReader.java:389)
	at com.t_oster.liblasercut.drivers.GenericGcodeDriver.waitForLine(GenericGcodeDriver.java:360)
	at com.t_oster.liblasercut.drivers.SmoothieBoard.waitForLine(SmoothieBoard.java:61)
	at com.t_oster.liblasercut.drivers.GenericGcodeDriver.sendLine(GenericGcodeDriver.java:335)
	at com.t_oster.liblasercut.drivers.GenericGcodeDriver.line(GenericGcodeDriver.java:298)
	at com.t_oster.liblasercut.drivers.GenericGcodeDriver.writeVectorGCode(GenericGcodeDriver.java:249)
	at com.t_oster.liblasercut.drivers.GenericGcodeDriver.sendJob(GenericGcodeDriver.java:575)
	at com.t_oster.visicut.VisicutModel.sendJob(VisicutModel.java:723)
	at com.t_oster.visicut.gui.MainView$61.run(MainView.java:1843)
```
When this happens, it is always in the same spot. I have a log file of me executing the exact same file about 10 times in a row, the error only happens about 3 times but is always on the same line of gcode.  It is possible that this error is a hardware/firmware issue, but since it is always on the same line of gcode, I am suspecting a software issue. 
If you would like to see the log file, it is posted at https://gist.github.com/13fb8036b0f188e9e70f.git .

The file I am using, is just the example 20mm circle, expanded to 150mm and saved as a new file. 

Thanks for all of your quick fixes, things are improving nicely. Keep up the good work!

**Comment by Tamagotono** [comment]
Latest update.
I have tried this with another Smoothie compatible board and am not getting the `java.io.IOException: Underlying input stream returned zero bytes` error with it (so far) so I am guessing that is a hardware issue with my other board. I'll try more testing later to make sure that is actually the case.

With this other board, I have a network jack and thus have been able to avoid the issues with the serial port not being released (which does happen on this board and USB). Using a network cable, everything seems to be working except engraving, this time. I am getting the exact opposite error that I had with cutting, earlier. Here is the output when I try to do an engraving (same result regardless of USB or Network).
```
< Smoothie command shell
> G21
< > ok
> G90
< ok
> M3
< ok
java.lang.ClassCastException: com.t_oster.liblasercut.PowerSpeedFocusProperty cannot be cast to com.t_oster.liblasercut.FloatPowerSpeedFocusProperty
        at com.t_oster.liblasercut.drivers.GenericGcodeDriver.writeVectorGCode(GenericGcodeDriver.java:252)
        at com.t_oster.liblasercut.drivers.GenericGcodeDriver.sendJob(GenericGcodeDriver.java:575)
        at com.t_oster.visicut.VisicutModel.sendJob(VisicutModel.java:723)
        at com.t_oster.visicut.gui.MainView$61.run(MainView.java:1843)
```

I will likely be swapping boards so I have a network enabled board in my laser cutter, so I can have it up and running without the serial port issues. I would still like to help test to get those corrected as well.

Thanks again for your help.

**Comment by t-oster** [comment]
Yes, I did not respect engraving with the latest update. I will fix this soon, but I won't have time until next week probably. I will also check for the port-locking, if I can reproduce it...

**Comment by Tamagotono** [comment]
Thomas,
 No worries about the time. If you understand where the raster problem is,
could you tell me which files will need to be changed? I have a bit of
spare time and would like to see if I can fix the issue myself, though I
doubt I can. I have dabbled in programming multiple languages, but Java is
not one of them and I never got to be very good with the others :)
If you do not know which files will need to be modified, then don't waste
any time researching it, I'll just be patient.
Thanks again for all of the hard work you have put into this project.
Please let me know if there is anything I can do to help.

Jason

**Comment by t-oster** [comment]
I think I fixed it in 0fcd129, so just test if it works. I did not test the engraving algorithm though, so it migth be that the error is gone, but engraving does not work as expected yet. So feel free to test engraving in all aspects. I would start with small parts, because converting the raster to G-Code bloats the whole job and I don't know where the limits are. Maybe the smoothieboard has/will get a more efficient representation of raster-lines, like the LAOS board has.

**Comment by Tamagotono** [comment]
I have been messing around with the code and realized that I hadn't given you the results of my test.
The edits you made changed the error, but did not fix the problem.  I am now getting the following error whenever I try to do a raster job.
``` < Smoothie
> G21
< ok
> G90
< ok
> M3
< ok
java.lang.ClassCastException: java.lang.Integer cannot be cast to java.lang.Float
	at com.t_oster.liblasercut.FloatPowerSpeedFocusProperty.setProperty(FloatPowerSpeedFocusProperty.java:134)
	at com.t_oster.liblasercut.drivers.GenericGcodeDriver.sendJob(GenericGcodeDriver.java:591)
	at com.t_oster.visicut.VisicutModel.sendJob(VisicutModel.java:723)
	at com.t_oster.visicut.gui.MainView$61.run(MainView.java:1843)```

I did, however, manage to figure out a fix for the port getting tied up. I simply added a bit of code (copy and paste from another section) to close the port we want to use, then wrapped it in a "try" and fail silently. If the port is open due to a prior crash or problem, it gets closed before we try to open it again. I have done a pull-request if you want to implement my "fix". It seems to work reliably, even when I force an error, I can always regain control of the port.  As I said, I have never programmed in Java before, so my "fix" may be overkill or even a really bad idea, for reasons I am not familiar with, but I hope it helps.

I will keep trying to figure out what is going on with the raster code, but it is not making a lot of sense to me (again, not familiar with Java), but that is the best way to learn. :)

**Comment by t-oster** [comment]
Looks like I just forgot to type 0 to 0.0f, so my last commit may fix this.
If your port-not-closed error is only triggered by visicut crashing, maybe avoiding that crashing is the solution. So if no exceptions occur anymore, the port will be correctly closed by the "disconnect" mehtod, and everybody is happy ;)

**Comment by Tamagotono** [comment]
Looks like that fixed the raster problem.
I do get the occasional `java.io.IOException: Underlying input stream
returned zero bytes` errors which (i believe) lock the port, but I need to
verify that.  I know that preventing the problems are the best way, but I
always like to have a backup solution for any unforeseen issues.
My day job is being a Reliability Technician so I am always looking for
ways of mitigating problems before the customer can find them, so I may be
a bit on the paranoid side. :)

Thanks again for all of your work, and taking time to fix this even though
you are very busy. It is much appreciated.

**Comment by t-oster** [comment]
Hi, what is the status of this build? Did anyone test it on windows and OSX? What needs to be done before migrating into the main build?

**Comment by Tamagotono** [comment]
Thomas,
 I have only tested the Linux version and I believe it had a couple of
hiccups but no major issues. I cannot recall what those issues were, as I
have not had the time to even turn on my machine in the last couple of
weeks. I do remember that using the network jack was much easier to use
than using USB, but I can't remember why...
I think I still have some Windows VMs on a drive somewhere if you would
like me to test with one of those, I would be happy to do so. What version
of Windows would you prefer the testing be done with?

I'll try to fire up the laser tonight and document the problems I find.
Hopefully I will have a list of issues later tonight and you can decide if
any of them are show-stoppers or not.

**Comment by Tamagotono** [comment]
Thomas,
 Here are the issues I was able to identify, this evening. This was only
tested under Linux, as I only had a short time to work on this. I'll report
more as I find them.

 * USB: java.io.IOException: Port in use /dev/ttyACM0 when retrying after
failed job

 * USB: java.io.IOException: Underlying input stream returned zero bytes

 * NETWORK: Movements are quick, but delay between each one, run same file
under USB and it works normal speed but gets the previous error. A job that
takes 3 minutes via USB takes about an hour via Network. This is the first
time I have seen this, but has been consistent. I have tried power cycling
both the smoothieboard and my computer at the same time, and the problem
persists. Tomorrow, I will try resetting the visicut configuration files to
see if that is the problem.

 * NETWORK: If smoothieboard crashes/is reset during a print, visicut does
not know to stop the job.

 * Visicut does not know how to handle if smoothieboard responds with !!
 (happens when "return_error_on_unhandled_gcode" is set to "true" in
smoothieboard config file and an unknown command is issued)

 * Visicut crashes and reports "GCODE-WARNING: No real circle" if you try
to load a .gcode file

 * If you select a different laser cutter, while running a job, the
"execute" button gets re-enabled. If the newly selected cutter is the same
as the first (one network the other USB) it is possible to send two sets of
commands to the same laser cutter, with bad results. This is not common to
have happen, but definitely possible.

**Comment by quillford** [comment]
The `java.io.IOException: Underlying input stream returned zero bytes ` error doesn't seem to be a smoothie issue. I am getting the same thing on Marlin & RAMPS 1.4. It always happens after 21 commands are sent.

**Comment by quillford** [comment]
#25 should fix 'java.io.IOException: Underlying input stream returned zero bytes'

**Comment by quillford** [comment]
20 second timeout seems to be optimal - at least for my 300x200mm laser. (I am basing it off of homing as that seems to take the longest time.) It may be a good idea to implement a setting for long running  gcode such as G28 which would have VisiCut expect a response less immediately than usual.

**Comment by quillford** [comment]
I think you can check off OS X from testing the serial library. I tested all the stuff I added on OS X. I've gone through a few dozen jobs with absolutely no issues besides the timeout being set too low (`java.io.IOException: Underlying input stream returned zero bytes `).

**Comment by BMac099** [comment]
Just checked x/y invert this did not change the scale on the preview.

**Comment by t-oster** [comment]
@BMac099 it should not change it on the preview. It is only if your lasercutter cuts upside-down or flipped. VisiCut assumes the origin to be top-left. Otherwise you have to use the setting

**Comment by BMac099** [comment]
If you define y to increment as it moves up the page shouldn't the graphic reflect it, if it doesn't why show it at all?

**Comment by t-oster** [comment]
I do define Y to increment as it moves DOWN the page in visicut. This is fixed and shown correctly and all the images are parsed this way. But if your Lasercutter's origin is on the bottom, it will interpret Y to increment as it goes UP the page, so it would cut your file upside down. If you use the setting in the driver, your drawing will be inverted before sent to the lasercutter. This has nothing to do with the preview.

**Comment by t-oster** [comment]
In order to organize this long pull request, please report every issue now separately as new issue. I think it's time to get this driver production ready.

**Comment by zendesigner01** [comment]
HI, Just started testing with your driver.  I have a K40 upgraded to a real smoothie X5 board. my test for now have brought following remarks.

1) Visicut preview is top left, and k40 origin is top left but X and Y axes seem to be swapped. SO when printing a model top left in visicut, it print bottom left to top left in the printer. 

2) When starting the first job over ethernet, the laser immediatly starts, after the job is finished it returns home.  Starting any subsequent job displays ," your job has been send , press start on the smoothie board" message.  But nowhere in the LCD panel or button is a button to start the job. So need to completely restart the entire pc after each job. 

3) When only wanting to engrave a model. Visicut always displays " your job has been send , press start on the smoothie board" message. so same issue. Can't start engraving jobs.

4) when including an engraving pass in the phone standard example file.  Put the pass to "everything else" "engrave" speed 100, power 20.  The Laser cutter just skips this pass and returns home for the end of the job. (profiles from fablab aachen , with only changed laser cutter)

SOme issues have been reported above in a similar way. I don't know how to make new issues on github, i just registered. 
Bart

**Comment by t-oster** [comment]
I am moving the driver to the develop branch, and I suggest to create every bug now as separate issue, so it is easier to keep an overview

**Pull request merged**
