### PR TITLE
New VectorOptimizer: DeleteDuplicatePathsOptimizer

### PR DESCRIPTION
**Pull request by renebohne**
I tested the optimizer with this SVG file:
http://hci.rwth-aachen.de/~bohne/poti.svg

It removes the duplicates and sorts the remaining, unique elements with the NEAREST strategy.

### CODE REVIEW

**Comment by t-oster** [comment]
The "DeleteDuplicatePathsOptimizer" file needs to have a ".java"-ending.

**Comment by t-oster** [comment]
rewritten in 6cf76932bb9028c1079ea6f7b97b57df067bebf2

**Comment by renebohne** [comment]
this feature does not seem to show up in the latest VisiCut version.
The optimizer does not show up in the VisiCut dialog...

**Comment by t-oster** [comment]
sorry, I forgot to update LibLaserCut on the build-server. please re-download and try again.

**Pull request closed without merging**
