### PR TITLE
Code Cleanup assisted by IntelliJ IDEA

### PR DESCRIPTION
**Pull request by phdoerfler**
Replaced invocations of deprecated API with their new counterparts, converted anonymous classes to lambdas, added a few type parameters, used List's sort instead of Collections.sort, removed superfluous generic type parameters, used Double.compare instead of creating new Double instances and comparing those (which internally uses Double.compare anyway), replaced for loops with Java 5 enhanced for loops, used resource aware try.

### CODE REVIEW

**Comment by mgmax** [comment]
There are a few conflicts, could you please rebase? Then I'll merge quickly.

**Comment by phdoerfler** [comment]
should be done :)

**Comment by phdoerfler** [comment]
> should be done :)

I knew I shouldn't have said that

**Comment by mgmax** [comment]
Looks like you accidentally restored some functions that were deleted.

**Comment by phdoerfler** [comment]
> Looks like you accidentally restored some functions that were deleted.

Ah that would explain it. I think my merge tool showed the local as remote changes and vice versa so to me it looked like those functions were added.

**Comment by phdoerfler** [comment]
Apparently during a rebase git on my machine does indeed label my changesets as "remote" and the incoming changesets as "local". I smell leaky abstraction.

**Comment by mgmax** [comment]
thanks :-)

**Pull request merged**
