### PR TITLE
Add absolute speed option for Smoothieboard driver

### PR DESCRIPTION
**Pull request by pelrun**
Adds new Smoothie driver that changes the meaning of the Speed variable from percent to mm/min.

Needs more work, don't merge just yet.

https://github.com/t-oster/VisiCut/issues/381

### CODE REVIEW

**Comment by pelrun** [comment]
Thinking about it more, since this doesn't update the profiles (i.e. toggling it breaks everything), it might be better to have it as a separate driver rather than a driver option, to force the profiles to be rewritten.

**Comment by mgmax** [comment]
As this is also applicable to all other GenericGcode based drivers, it would perhaps be better to make this a configuration option inside GenericGcodeDriver, named something like "Absolute speed (change will break existing settings)". It would also make the code easier to understand, if setSpeed just contains an if/else logic.

The configuration dialog even allows changing the driver, so we cannot prevent the user from switching the option anyway.

The Epilog driver is not based on Gcode, so it would still work as before.

**Comment by pelrun** [comment]
I don't like having an option break all the profiles, especially when you can't then tell which ones have been updated. But I'm not happy with having multiple drivers either. The option needs to either auto-update the profiles, or just change how they're displayed. I'll look at doing the latter.

**Comment by madleech** [comment]
Cool feature, I'd be very interested in having this as a general option for all gcode drivers.

**Comment by t-oster** [comment]
I am not sure, if it is such a problem that it breaks the profiles, because if you are messing with the driver settings, you should know what you are doing anyway... 
....@madleech nice avatar....

**Comment by pelrun** [comment]
It's still a UI failure. And fixing those has been the main focus of my work on VisiCut.

**Comment by t-oster** [comment]
Hi, what is the state of this patch? I think adding it to the generic gcode driver is a good option

**Comment by pelrun** [comment]
I'm not happy with it, and I didn't get far trying to resolve the issues that popped up. The big one was that the displayed text for the "power/speed/focus" options is magic and used as a key for serialisation. So I couldn't readily just change those dynamically to include units, because it breaks everything.

It did occur to me you can be super sneaky and just change the max speed in the driver to 6000 mm/min, at which point the percentage is also numerically identical to the speed in mm/s...

**Comment by t-oster** [comment]
but it will only allow values between 0 and 100, right?

**Comment by pelrun** [comment]
It's just a trick, not really a good solution :)

**Comment by pelrun** [comment]
I'm having another stab at this, although the implementation is significantly different now - so I'll close this PR and raise a new one if/when I get it working.

**Pull request closed without merging**
